# Generated by Django 3.1.7 on 2022-12-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
