# Generated by Django 3.1.7 on 2022-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_api', '0002_auto_20221208_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
